AWSTemplateFormatVersion: 1010-09-09

Parameters:
  MCCodePipelineBucket:
    Type: String
    Description: 'The S3 bucket for CodePipeline artifacts.'

Resources:
  MCCodePipelineS3Bucket:
    Type: AWS::S3::Bucket
    # Keep this resource when its stack is deleted
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref MCCodePipelineBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
            # SSE = server-side encryption
            SSEAlgorithm: AES256
